# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cool-darts-web CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client
    steps:
    - run: yarn test
